### ISSUE TITLE
Issue while generating signed strings with developer key (HTTP 405)

### ISSUE THREAD

**Issue by LeeviHalme** [willfrew/node-random-org#10]
I'm getting an HTTP error while using the `generateSignedStrings()` method. I'm using the free Developer API key. Keep in mind that this doesn't happen with a migrated Beta API key.

Console output:

`
{ Error: The API key you specified is not valid for the version of the API you are invoking
    at path\to\node_modules\random-org\src\RandomOrg.js:62:23
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 405 }
`

**Comment by willfrew** [comment]
Oo interesting, thanks for reporting this. I suspect this is due to the fact we're still by default hitting the v1 endpoint.

I'll try to take a look at properly switching to the new endpoint soon but could you try the workaround mentioned in #9 for now?

**Comment by LeeviHalme** [comment]
> Oo interesting, thanks for reporting this. I suspect this is due to the fact we're still by default hitting the v1 endpoint.
> 
> I'll try to take a look at properly switching to the new endpoint soon but could you try the workaround mentioned in #9 for now?

That fix works for now, thanks!
