### ISSUE TITLE
Support new v2 api methods

### ISSUE THREAD

**Issue by willfrew** [willfrew/node-random-org#13]
The new api version added a few additional methods and parameters ([docs here](https://api.random.org/json-rpc/2/fundamentals)).

**Comment by Gameghostify** [comment]
This can be closed now, right?

**Comment by willfrew** [comment]
Not yet - currently we support hitting the new api endpoint but not with the newly added methods. New params on existing methods may work fine though.

I'm not sure exactly when i'll get around to this - it's a fairly small change though so if someone gets there first / needs these new methods please feel free to send a PR!

**Comment by willfrew** [comment]
Fixed in v2.1.0
